<a href="https://www.kaggle.com/code/notsau/zingat-regression?scriptVersionId=161443851" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("zingat_data.csv", encoding="latin1")

# EDA

In [3]:
df.head()

,Unnamed: 0,ÝLAN ADI,MAHALLE,FÝYAT,NET(m²),BRÜT(m²),ODA-SALON SAYISI,ODA SAYISI,BANYO SAYISI,FOTOÐRAF SAYISI
0,0,PAZARTEKKE 2+1 KÝRALIK DAÝRE,Mevlanakapý,13.0,85,95,2+1,2,1,7.0
1,1,Vatan Caddesine 5 dk harika lokasyonda 2+1,Molla Gürani,12.5,90,110,2+1,2,1,16.0
2,2,Çapada Turgut Özal Millet Caddesinde Kiralýk 3...,Þehremini,24.0,120,140,3+1,3,1,NaN
3,3,KARAGÜMRÜK MERKEZÝ KONUM BALKONLU 3.KAT DAÝRE,Karagümrük,15.0,85,95,2+1,2,1,16.0
4,4,CERRAHPAÞA'DA 2+1 EÞYALI KLÝMALI HASTANELERE Y...,Cerrahpaþa,15.0,80,90,2+1,2,1,15.0

In [4]:
df.isnull().sum()

Unnamed: 0            0
ÝLAN ADI              0
MAHALLE               0
FÝYAT                 0
NET(m²)               0
BRÜT(m²)              0
ODA-SALON SAYISI      0
ODA SAYISI            0
BANYO SAYISI          0
FOTOÐRAF SAYISI     120
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>

RangeIndex: 868 entries, 0 to 867

Data columns (total 10 columns):

 #   Column            Non-Null Count  Dtype

---  ------            --------------  -----

 0   Unnamed: 0        868 non-null    int64

 1   ÝLAN ADI          868 non-null    object

 2   MAHALLE           868 non-null    object

 3   FÝYAT             868 non-null    float64

 4   NET(m²)           868 non-null    object

 5   BRÜT(m²)          868 non-null    object

 6   ODA-SALON SAYISI  868 non-null    object

 7   ODA SAYISI        868 non-null    object

 8   BANYO SAYISI      868 non-null    object

 9   FOTOÐRAF SAYISI   748 non-null    float64

dtypes: float64(2), int64(1), object(7)

memory usage: 67.9+ KB

# Feature Engineering

In [6]:
del df["Unnamed: 0"]

In [7]:
df["BRÜT(m²)"].unique()

array(['95', '110', '140', '90', '80', '85', '65', '60', '75', '55',
       '120', '360', '83', '70', '61', '105', '100', '185', '72', '-',
       '150'], dtype=object)

In [8]:
df["BRÜT(m²)"] = pd.to_numeric(df["BRÜT(m²)"], errors="coerce")
df["BRÜT(m²)"].fillna(0, inplace=True)

In [9]:
df["NET(m²)"].unique()

array(['85', '90', '120', '80', '75', '60', '50', '100', '70', '135',
       '42', '110', 'Yarým Kagir', '68', '55', '95', '150', '75m²',
       '720m²', '65', '140'], dtype=object)

In [10]:
df["NET(m²)"] = df["NET(m²)"].replace("75m²", "75")
df["NET(m²)"] = df["NET(m²)"].replace("720m²", "720")
df["NET(m²)"] = pd.to_numeric(df["NET(m²)"], errors="coerce")
df["NET(m²)"].fillna(0, inplace=True)

In [11]:
df["NET(m²)"] = df["NET(m²)"].replace("m²", "")
df["BRÜT(m²)"] = pd.to_numeric(df["BRÜT(m²)"], errors="coerce")
#errors="coerce" sayısal olmayan değerleri NaN ile değitirir
df["BRÜT(m²)"].fillna(0, inplace=True)

In [12]:
df["FOTOÐRAF SAYISI"].fillna(0, inplace=True)

In [13]:
df["ODA-SALON SAYISI"].unique()

array(['2+1', '3+1', '1+1', '345', '4+1', '4', '0 TL'], dtype=object)

In [14]:
df["ODA-SALON SAYISI"] = df["ODA-SALON SAYISI"].replace("2+1", "3")
df["ODA-SALON SAYISI"] = df["ODA-SALON SAYISI"].replace("3+1", "4")
df["ODA-SALON SAYISI"] = df["ODA-SALON SAYISI"].replace("1+1", "2")
df["ODA-SALON SAYISI"] = df["ODA-SALON SAYISI"].replace("345", "5")
df["ODA-SALON SAYISI"] = df["ODA-SALON SAYISI"].replace("4+1", "5")
df["ODA-SALON SAYISI"] = df["ODA-SALON SAYISI"].replace("0 TL", "0")

In [15]:
df["ODA SAYISI"].unique()

array(['2', '3', '1', '345', '4', '0 TL'], dtype=object)

In [16]:
df["ODA SAYISI"] = df["ODA SAYISI"].replace("0 TL", "0")
df["ODA SAYISI"] = df["ODA SAYISI"].replace("345", "5")

In [17]:
df["BANYO SAYISI"].unique()

array(['1', '2', '345 (m²)', '0', '3', '21-25 arasý', 'Hayýr'],
      dtype=object)

In [18]:
df["BANYO SAYISI"] = df["BANYO SAYISI"].replace("345 (m²)", "345")
df["BANYO SAYISI"] = df["BANYO SAYISI"].replace("21-25 arasý", "23")
df["BANYO SAYISI"] = df["BANYO SAYISI"].replace("Hayýr", "0")

In [19]:
df["FOTOÐRAF SAYISI"].unique()

array([ 7., 16.,  0., 15.,  9., 21., 13., 19., 14., 30., 26., 10., 24.,
       29., 17., 36.,  5.,  6.,  3., 12., 33., 20.,  4.,  8., 31.])

In [20]:
df["FÝYAT"] = df["FÝYAT"].astype(int)
df["NET(m²)"] = df["NET(m²)"].astype(int)
df["BRÜT(m²)"] = df["BRÜT(m²)"].astype(int)
df["ODA-SALON SAYISI"] = df["ODA-SALON SAYISI"].astype(int)
df["ODA SAYISI"] = df["ODA SAYISI"].astype(int)
df["BANYO SAYISI"] = df["BANYO SAYISI"].astype(int)
df["FOTOÐRAF SAYISI"] = df["FOTOÐRAF SAYISI"].astype(int)

In [21]:
df["FÝYAT"]=df["FÝYAT"]*1000

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>

RangeIndex: 868 entries, 0 to 867

Data columns (total 9 columns):

 #   Column            Non-Null Count  Dtype

---  ------            --------------  -----

 0   ÝLAN ADI          868 non-null    object

 1   MAHALLE           868 non-null    object

 2   FÝYAT             868 non-null    int32

 3   NET(m²)           868 non-null    int32

 4   BRÜT(m²)          868 non-null    int32

 5   ODA-SALON SAYISI  868 non-null    int32

 6   ODA SAYISI        868 non-null    int32

 7   BANYO SAYISI      868 non-null    int32

 8   FOTOÐRAF SAYISI   868 non-null    int32

dtypes: int32(7), object(2)

memory usage: 37.4+ KB

In [23]:
df.head()

,ÝLAN ADI,MAHALLE,FÝYAT,NET(m²),BRÜT(m²),ODA-SALON SAYISI,ODA SAYISI,BANYO SAYISI,FOTOÐRAF SAYISI
0,PAZARTEKKE 2+1 KÝRALIK DAÝRE,Mevlanakapý,13000,85,95,3,2,1,7
1,Vatan Caddesine 5 dk harika lokasyonda 2+1,Molla Gürani,12000,90,110,3,2,1,16
2,Çapada Turgut Özal Millet Caddesinde Kiralýk 3...,Þehremini,24000,120,140,4,3,1,0
3,KARAGÜMRÜK MERKEZÝ KONUM BALKONLU 3.KAT DAÝRE,Karagümrük,15000,85,95,3,2,1,16
4,CERRAHPAÞA'DA 2+1 EÞYALI KLÝMALI HASTANELERE Y...,Cerrahpaþa,15000,80,90,3,2,1,15

In [24]:
new_df = pd.get_dummies(df, columns=["MAHALLE"])
new_df.drop(columns="ODA-SALON SAYISI", inplace=True)
new_df.drop(columns="ÝLAN ADI", inplace=True)
new_df = new_df.astype(int)
new_df

,FÝYAT,NET(m²),BRÜT(m²),ODA SAYISI,BANYO SAYISI,FOTOÐRAF SAYISI,MAHALLE_Aksaray,MAHALLE_Akþemsettin,MAHALLE_Atikali,MAHALLE_Ayvansaray,...,MAHALLE_Mevlanakapý,MAHALLE_Molla Gürani,MAHALLE_Seyyid Ömer,MAHALLE_Silivrikapý,MAHALLE_Sümbül Efendi,MAHALLE_Topkapý,MAHALLE_Yedikule,MAHALLE_Zeyrek,MAHALLE_Ýskenderpaþa,MAHALLE_Þehremini
0,13000,85,95,2,1,7,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,12000,90,110,2,1,16,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,24000,120,140,3,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,15000,85,95,2,1,16,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,15000,80,90,2,1,15,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
863,24000,85,95,2,1,10,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
864,19000,100,110,3,1,24,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
865,25000,100,110,3,1,21,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
866,15000,70,90,2,1,29,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
867,13000,42,55,1,1,30,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [25]:
new_df.sort_values("FÝYAT")

,FÝYAT,NET(m²),BRÜT(m²),ODA SAYISI,BANYO SAYISI,FOTOÐRAF SAYISI,MAHALLE_Aksaray,MAHALLE_Akþemsettin,MAHALLE_Atikali,MAHALLE_Ayvansaray,...,MAHALLE_Mevlanakapý,MAHALLE_Molla Gürani,MAHALLE_Seyyid Ömer,MAHALLE_Silivrikapý,MAHALLE_Sümbül Efendi,MAHALLE_Topkapý,MAHALLE_Yedikule,MAHALLE_Zeyrek,MAHALLE_Ýskenderpaþa,MAHALLE_Þehremini
668,9000,50,60,1,1,19,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
311,9000,50,60,1,1,19,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
164,9000,50,60,1,1,19,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
815,9000,50,60,1,1,19,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
374,9000,50,60,1,1,19,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35,26000,85,100,2,1,29,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36,28000,150,185,4,3,33,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
23,60000,0,360,5,345,36,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
43,95000,75,0,4,23,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,325000,720,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

# Modelling

In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import RidgeCV
import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn.model_selection import train_test_split
from pandas import Series, DataFrame
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
import patsy

In [27]:
x = new_df.iloc[:,1:]
y = new_df.iloc[:,:1]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=20)
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.25, random_state=20)

lr_model = LinearRegression()

lr_model.fit(x_train,y_train)
pred = lr_model.predict(x_val)

print("MSE Value: ", np.mean((pred - y_val)**2), "\n")

print("R^2 Score Value (Test): ", lr_model.score(x_test, y_test), "\n")

print("R^2 Score Value (Validation): ", lr_model.score(x_val, y_val), "\n")

print("Coefficients:\n", lr_model.coef_)

MSE Value:  FÝYAT    4.385925e+06

dtype: float64



R^2 Score Value (Test):  0.8170281158447273



R^2 Score Value (Validation):  0.8017660680777475



Coefficients:

 [[  440.81375025  -435.53335127  7740.47175899   488.28208628

    -30.90690807  4503.7323799  -5542.277266     836.37239484

   7136.71241871 12776.32896986  -337.10183559 -5647.40605062

   2002.25987433 -2660.29330593 -5479.32477032  -551.53207338

   8481.96162917 -2331.37648134   198.78006818 -5688.71456454

  -1688.05676609 -2106.01023402 -2850.23966755 -6576.58240809

   5830.44584359 -3032.51203249  2724.83387739]]

C:\Users\slymn\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:3462: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'

  return mean(axis=axis, dtype=dtype, out=out, **kwargs)

In [28]:
import pickle
#modeli pickle olarak kaydetmek için

In [31]:
pickle.dump(lr_model,open("evfiyat.pkl","wb"))
#modeli seç ve aç, maas diye kaydet, wb(write=yaz)

In [32]:
yenimodel=pickle.load(open("evfiyat.pkl","rb"))
#modeli yükle ve aç, maas adlı model, rb(read=oku)

In [33]:
pd.set_option('display.max_columns', None)

In [35]:
x.head()

,NET(m²),BRÜT(m²),ODA SAYISI,BANYO SAYISI,FOTOÐRAF SAYISI,MAHALLE_Aksaray,MAHALLE_Akþemsettin,MAHALLE_Atikali,MAHALLE_Ayvansaray,MAHALLE_Balat,MAHALLE_Cerrahpaþa,MAHALLE_Derviþ Ali,MAHALLE_Emin Sinan,MAHALLE_Haseki Sultan,MAHALLE_Hýrka-i Þerif,MAHALLE_Karagümrük,MAHALLE_Koca Mustafapaþa,MAHALLE_Mevlanakapý,MAHALLE_Molla Gürani,MAHALLE_Seyyid Ömer,MAHALLE_Silivrikapý,MAHALLE_Sümbül Efendi,MAHALLE_Topkapý,MAHALLE_Yedikule,MAHALLE_Zeyrek,MAHALLE_Ýskenderpaþa,MAHALLE_Þehremini
0,85,95,2,1,7,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
1,90,110,2,1,16,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
2,120,140,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
3,85,95,2,1,16,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
4,80,90,2,1,15,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [36]:
yenimodel.predict([[60,70,2,1,10,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]])
#yeni modelde sırayla sütunları girip fiyat'i tahmin ettiriyoruz

C:\Users\slymn\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names

  warnings.warn(

array([[19889.76077632]])